# This is a basic workflow to help you get started with Actions

name: Deploy github page

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v4

      # install node.js
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22.11"

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: npm install

      # Runs a single command using the runners shell
      - name: Build the project
        run: npm run build

      # use actions-gh-pages to deploy dist to gh-pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          # github will auto-generate a token for this job and use it
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
